### ISSUE TITLE
Parity program crashes with "BufferUnderflowException" when Parity Sim is executed on windows.

### ISSUE THREAD

**Issue by meghraj27** [paritytrading/parity-extras#9]
Main Parity System program was running fine with default settings(only FOO instrument was added),
then I executed Parity Sim(with provided default config file), following is the out put for Parity Sim:

```
D:\work\parity\parity-extras-master\applications\sim>java -jar parity-sim.jar etc\devel.conf
fatal: An existing connection was forcibly closed by the remote host

java.io.IOException: An existing connection was forcibly closed by the remote host
        at sun.nio.ch.SocketDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(Unknown Source)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
        at sun.nio.ch.IOUtil.read(Unknown Source)
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
        at com.paritytrading.nassau.soupbintcp.SoupBinTCPSession.receive(SoupBinTCPSession.java:86)
        at com.paritytrading.parity.sim.Events.run(Events.java:67)
        at com.paritytrading.parity.sim.Simulator.main(Simulator.java:55)
        at com.paritytrading.parity.sim.Simulator.main(Simulator.java:26)
```

and, in the Parity System console(after crashing due to Parity Sim execution):

```
D:\work\parity\parity-0.7.0\applications\system>java -jar parity-system.jar etc\example.conf
Exception in thread "main" java.nio.BufferUnderflowException
        at java.nio.Buffer.nextGetIndex(Unknown Source)
        at java.nio.HeapByteBuffer.getLong(Unknown Source)
        at com.paritytrading.parity.net.poe.POE$EnterOrder.get(POE.java:72)
        at com.paritytrading.parity.net.poe.POEServerParser.message(POEServerParser.java:37)
        at com.paritytrading.nassau.soupbintcp.SoupBinTCPServer.packet(SoupBinTCPServer.java:148)
        at com.paritytrading.nassau.soupbintcp.SoupBinTCPSession.parse(SoupBinTCPSession.java:125)
        at com.paritytrading.nassau.soupbintcp.SoupBinTCPSession.receive(SoupBinTCPSession.java:93)
        at com.paritytrading.parity.system.Events.receive(Events.java:95)
        at com.paritytrading.parity.system.Events.run(Events.java:68)
        at com.paritytrading.parity.system.TradingSystem.main(TradingSystem.java:47)
        at com.paritytrading.parity.system.TradingSystem.main(TradingSystem.java:27)
```

I am using windows 10,  with java 8:
```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

Please provide solution

**Comment by jvirtanen** [comment]
Hi @meghraj27! A good catch, Parity Extras is unfortunately not yet updated to be compatible with Parity 0.7.0, the latest version. I'll put this on the backlog. In the meantime, you can use Parity 0.6.0 instead _or_ you can check out [Genesis](https://github.com/jvirtanen/genesis) which is based on Parity 0.7.0 and uses real-time market data from [GDAX](https://www.gdax.com).

**Comment by jvirtanen** [comment]
I opened #10 for upgrading Parity Extras to Parity 0.7.0.
